### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Max44444** [Max44444/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Max444444** [comment]
- Hello, everyone!
My name is Max and I am a student of the KPI National Technical University of Ukraine. For almost two years now, I have enjoyed studying information systems and technologies. At this point I am interested in learning and developing my skills in web development, namely the development of web applications on the Java platform.

**Comment by Max44444** [comment]
Nice work
