### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Max44444** [Max44444/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Max444444** [comment]
- [github](https://github.com/Max44444)
- skorokhodov.maxim.444@gmail.com
- [telegram](https://t.me/S_010011010110000101111000)
- +38 (098)-551-66-46

**Comment by Max44444** [comment]
Completed
