### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Max44444** [Max44444/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Max444444** [comment]
- 1 September 2019 - present : student of Kyiv Polytechnic Institute
_Study software engineering, programming, databases. Make simple console and web applications. Study math, physics, probability theory and other_

- 1 October 2020 - present - student of Green Forest English school

- 1 September 2008 - 31 May 2019 : school life
