### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Max44444** [Max44444/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Max444444** [comment]
**LANGUAGES**
UKRAINIAN, RUSSIAN, ENGLISH

**SKILLS**
 - Java, Maven, Basics of Spring Beans, Spring MVC, Spring Security, Unit Test
 - Html, Css, Scss, Sass, Bootstrap, JavaScript, NodeJs, NPM, WebPack, Angular, React
 - PostgreSQL, Basics of MongoDB
 - Rest API, Websocket, Networking
 - OOP, GoF Patterns, MVC, UML, Agile methodologies

**CHARACTER**
HUMBLE, HONEST, CONFIDENT, CURIOUS, STUBBORN

**LIKES**
ROCK POP INDIE MUSIC, DRAMA MYSTERY SCI-FI MOVIES, HUMOR, PLAY THE GUITAR, TESLA, PIZZA, MONEY, TECHNOLOGIES

**DISLIKE**
BAD HABITS, POLITICS, STUPID PEOPLE, VIOLENCE ON ANIMAL, WAR, BUREAUCRACY, QUARANTINE

**WANTS**
TRAVEL, TESLA, TO BE FIT AND HEALTHY, OWN COMPANY
